name: Build and Test PAM

run-name: ${{ github.actor }} is building PAM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pam-build-test:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      SHELL: /usr/bin/bash
      PIPENV_VENV_IN_PROJECT: 1
    steps:
      - name: required-packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y apt-utils
          sudo apt-get install -y tzdata
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential
          sudo apt-get install -y util-linux
          sudo apt-get install -y vim
          sudo apt-get install -y tree
          sudo apt-get install -y git
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          sudo apt-get install -y pandoc
          sudo apt-get install -y aspell
          sudo apt-get install -y curl
          sudo apt-get install -y wget
          sudo apt-get install -y zip
          sudo apt-get install -y lsof
          sudo apt-get install -y ripgrep
          sudo apt-get install -y jq
          sudo pip install pipenv
          pip --version
          pipenv --version
      - name: google-chrome
        run: |
          wget -vP /tmp/ https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          ls -l /tmp/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y --allow-downgrades /tmp/google-chrome-stable_current_amd64.deb
          which google-chrome
          google-chrome --version
      - name: chromedriver
        run: |
          CVER=$(google-chrome --version)
          VERSION=$(echo "$CVER" | awk '{print $NF}')
          echo "VERSION=$VERSION"
          MAJOR=$(echo "$VERSION" | tr '.' ' ' | awk '{print $1}')
          MINOR=$(echo "$VERSION" | tr '.' ' ' | awk '{print $2}')
          URL=$(wget https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json -O - -o /dev/null | jq . | rg "https://.*chromedriver-linux64" | tr '"' '\n' | grep "$MAJOR.$MINOR" | tail -1)
          echo "URL: $URL"
          wget "$URL" -O /tmp/x.zip
          unzip -l /tmp/x.zip
          ls -l /usr/bin/chromedriver
          sum /usr/bin/chromedriver
          rm -f /tmp/chromedriver
          unzip -p /tmp/x.zip '*/chromedriver' > /tmp/chromedriver
          sudo cp /tmp/chromedriver /usr/bin/chromedriver
          sudo chmod a+x /usr/bin/chromedriver
          /usr/bin/chromedriver --version
          rm -f /tmp/chromedriver
          ls -l /usr/bin/chromedriver
          sum /usr/bin/chromedriver
          /usr/bin/chromedriver --version
          rm -f /tmp/x.zip
          which chromedriver
          chromedriver --version
      - name: checkout-pam
        uses: actions/checkout@v2
        with:
          repository: jlinoff/pam
          path: './pam'
      - name: make help
        run: |
          cd pam
          make help
      - name: make build
        run: |
          cd pam
          make
      - name: make test
        run: |
          cd pam
          make test
      - name: make web
        run: |
          cd pam
          make web
          ls -l pam-www.tar
